server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: 123456
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: debug
