application:
  name: prod环境 @project.artifactId@
  version: prod环境 @project.version@
developer:
  name: prod环境 xkcoding
  website: prod环境 http://xkcoding.com
  qq: prod环境 237497819
  phone-number: prod环境 17326075631